services:
  airflow:
    image: apache/airflow:2.8.1
    container_name: weather-airflow
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      MINIO_ENDPOINT: http://host.docker.internal:9000
      MINIO_BUCKET: data-pipeline
      PYTHONPATH: /opt/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: boto3 pandas requests python-dotenv
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../config:/opt/airflow/config
      - ../.env:/opt/airflow/.env
      - airflow_data:/opt/airflow
    command: standalone

volumes:
  airflow_data:
